// Generated by https://quicktype.io

export interface IFacturaRequest {
    fechaEmision:      string;
    fechaPago:         string;
    diasTranscurridos: number;
    totalRecibir:      number;
    retencion:         number;
    diasxAnio:         number;
    plazoTaza:         number;
    tasaEfectiva:      number | string;
    fechaDescuent:     string;
    CyGI:              number;
    CyGF:              number;
    periodoCapital:    number | string;
    tasaNominal:       number | string;
    accountId:         number;
}
